export const projects = [
  {
    title: "Gasbot",
    description: "Multichain crypto refuel platform.",
    github: "",
    live: "https://gasbot.xyz",
    stack: "NextJS, TS, Tailwind, Viem",
    isPrivate: true,
  },
  {
    title: "Checkbot",
    description: "Accountability Slack bot.",
    github: "https://github.com/checkmate-africa/checkbot",
    live: "",
    stack: "Golang, Aws (Lambda, Api Gateway, SAM)",
    isPrivate: false,
    isRepository: true,
  },
  {
    title: "Petra Okelola",
    description: "Product designer portfolio.",
    github: "",
    live: "https://petraokelola.com",
    stack: "Nuxt3, TS, Gsap",
    isPrivate: true,
  },
  {
    title: "Guild Protocol",
    description: "Landing Page for a play to earn crypto DAO",
    github: "",
    live: "https://guildprotocol.io/",
    stack: "NextJS, TS, GSAP",
    isPrivate: true,
  },
  {
    title: "Caketools",
    description: "Decentralised charting hub for the BSC Network.",
    github: "",
    live: "https://caketools.vercel.app/",
    stack: "NextJS, TS, Ethers",
    isPrivate: true,
  },
  {
    title: "Pickr",
    description: "Custom a11y Compliant Datepicker.",
    github: "https://github.com/kadetXx/pickr",
    live: "https://620e47ad1a4db5003a4d7f8d-zfxvyoulnf.chromatic.com/?path=/story/pickr--default",
    stack: "React, TS, Emotion",
    isPrivate: false,
  },
  {
    title: "Tiny UI",
    description: "Mini component library with unit tests and storybook.",
    github: "https://github.com/kadetXx/tinyui-shared",
    live: "https://main--6564288785ce4d45c718c033.chromatic.com/",
    stack: "React, TS, Stitches, Jest",
    isRepository: true,
  },
  {
    title: "BevelPlexus",
    description: "Fintech Dashboard UI",
    github: "",
    live: "https://dev-bevelplexus.netlify.app/",
    stack: "React, Context API",
    isPrivate: true,
  },
  {
    title: "React Insect",
    description: "Customisable input & select dropdown component for react.",
    github: "https://github.com/kadetXx/insect",
    live: "https://www.npmjs.com/package/react-insect",
    stack: "React, TS",
    isPackage: true,
  },
  {
    title: "Birdbox",
    description: "Social application with real time Messaging.",
    github: "https://github.com/kadetXx/birdbox",
    live: "https://birdbox.vercel.app/",
    stack: "Vue, Web Sockets, Node JS",
    isPrivate: false,
  },
];
